version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      TERM: dumb
      CACHE_VERSION: 2
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    steps:
      - checkout
      - restore_cache:
          key: sc-core-tests-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}
      - run:
          name: "Download dependencies"
          command: ./mvnw -s .settings.xml -U --fail-never dependency:go-offline || true
      - save_cache:
          key: sc-core-tests-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}
          paths:
            - ~/.m2
      - run:
          name: "Running build"
          command: ./scripts/runAcceptanceTests.sh
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} ~/junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ~/junit/
          destination: artifacts
      - store_test_results:
          path: ~/junit/
          destination: testartifacts

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/fac69f6fc000ef14f7ec
