spring:
  application:
    name: stream-bus
  cloud:
    function:
      definition: you
  config:
    import: "optional:configserver:"
---
spring:
  config:
    activate:
      on-profile: other
server:
  port: 8081
